% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
  11pt,
]{article}
\usepackage{xcolor}
\usepackage[left=3cm,right=5cm,top=2cm,bottom=2cm]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
%% tools/stamp.tex
%% Provenance footer for PDFs rendered from this project.
%% Vendored by zzcollab; this file is not project-specific. The
%% footer prints the source document and the time of rendering.
%% The git version is defined here too, and so is available to a
%% project that wants it on the page, but it is left off the
%% default footer: it already names the staged copy in share/ and
%% appears in its manifest row. All values are supplied at render
%% time by tools/stamp-render.R, which writes a small generated
%% file that redefines the macros below. The \providecommand
%% defaults keep a bare LaTeX compile working when the document is
%% built without the wrapper.
\usepackage{fancyhdr}
\usepackage{xcolor}
\providecommand{\stampsource}{\detokenize{(source not recorded)}}
\providecommand{\stamptime}{(time not recorded)}
\providecommand{\stampversion}{\detokenize{(version not recorded)}}
\setlength{\footskip}{40pt}
\newcommand{\stampfootcontent}{%
  \footnotesize\color{gray}%
  \parbox[b]{\textwidth}{%
    \stamptime\hfill\thepage\\[2pt]%
    \ttfamily\raggedright\stampsource}}
\pagestyle{fancy}
\fancyhf{}
\fancyfoot[C]{\stampfootcontent}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0.4pt}
%% The title page uses the `plain` page style; redefine it so the
%% stamp appears there too.
\fancypagestyle{plain}{%
  \fancyhf{}%
  \fancyfoot[C]{\stampfootcontent}%
  \renewcommand{\headrulewidth}{0pt}%
  \renewcommand{\footrulewidth}{0.4pt}}
\renewcommand{\stampsource}{\textasciitilde{}/\allowbreak{}prj/\allowbreak{}res/\allowbreak{}07-multicenter-rct/\allowbreak{}multicenterrct/\allowbreak{}analysis/\allowbreak{}report/\allowbreak{}report.Rmd}
\renewcommand{\stamptime}{2026-08-14 12:53 PDT}
\renewcommand{\stampversion}{\detokenize{6d8f417-wip}}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{lineno}
\linenumbers
\usepackage{setspace}
\setstretch{1.1}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
% fallback for those not using the hyperref driver hyperxmp:
\makeatletter
\@ifundefined{xmpquote}{\newcommand{\xmpquote}[1]{#1}}{}
\makeatother
\hypersetup{
  pdftitle={Statistical Issues in Multicenter Randomized Clinical Trials},
  pdfauthor={Ronald G. Thomas, Ph.D.},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Statistical Issues in Multicenter Randomized Clinical Trials}
\author{Ronald G. Thomas,
Ph.D.\thanks{Wertheim School of Public Health, UCSD; ORCID: 0000-0003-1686-4965}}
\date{August 14, 2026}

\begin{document}
\maketitle
\begin{abstract}
Multicenter randomized controlled trials require a choice among
ignoring, fixing, or randomizing site effects in the primary analysis,
and this choice interacts with stratified-randomization adjustment,
treatment-by-site interaction, and site-size balance. We report a
factorial Monte Carlo simulation, structured under the ADEMP framework
of Morris, White, and Crowther (2019), that jointly varies the number of
sites, site-level variance, treatment-by-site interaction, and site-size
balance, comparing OLS ignoring site, OLS with fixed site effects, and a
linear mixed model with random site effects. In addition to bias,
empirical and model-based standard error, power, and coverage under a
true alternative treatment effect, we report empirical Type I error
under a true null effect, and singular/boundary-fit rates for the
random-effects model, both previously unreported in this simulation
design. The random-effects model attains the best combination of power
and coverage across most conditions; ignoring site produces conservative
(not anti-conservative) inference under stratified randomization,
consistent with prior work; and all three methods control Type I error
near the nominal level in the null-hypothesis scenarios simulated. For
the treatment-by-site-interaction scenarios, where the random-intercept
model is misspecified, we additionally fit and compare a random-slopes
model, finding consistently higher coverage but a substantially higher
singular-fit rate, a trade-off not previously quantified in this
simulation design. Every point estimate is reported with its Morris et
al.~Table 6 Monte Carlo standard error. Code and a full ADEMP audit
trail accompany the simulation.
\end{abstract}

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\section{Introduction}\label{introduction}

Multicenter randomized clinical trials (RCTs) represent the standard
design for confirmatory evaluation of therapeutic interventions. By
enrolling participants across multiple clinical sites, these trials
achieve practical recruitment targets while broadening the population
base for generalization of
findings\textsuperscript{\citeproc{ref-iche9}{1},\citeproc{ref-localio2001adjustments}{2}}.
However, the multicenter structure introduces several analytic
complexities that, if mishandled, can distort inference about treatment
effects. We address four interrelated statistical issues that arise in
the design and analysis of multicenter RCTs with continuous outcomes,
and we present simulation evidence bearing on each in turn.

\subsection{Modeling site effects}\label{modeling-site-effects}

The first question concerns how site (or center) effects should be
incorporated into the primary analysis. Three broad strategies exist:
ignoring site differences entirely, treating sites as fixed effects, and
treating sites as random effects drawn from a population of potential
sites. Each strategy carries distinct assumptions and implications for
the validity and efficiency of treatment effect
estimation\textsuperscript{\citeproc{ref-senn1998controversies}{3},\citeproc{ref-jones1998comparison}{4}}.

Localio and colleagues provided an influential overview of the problem,
identifying three analytic challenges inherent to multicenter data:
within-center correlation of outcomes, confounding by center, and effect
modification across
centers\textsuperscript{\citeproc{ref-localio2001adjustments}{2}}. The
choice between fixed and random effects models has been debated
extensively. Fixed effects models condition on the observed sites and
make no distributional assumptions about site effects, but they consume
degrees of freedom rapidly when the number of sites is large relative to
total sample
size\textsuperscript{\citeproc{ref-pickering2007analysis}{5}}. Random
effects models treat site effects as realizations from a normal
distribution, estimating only a variance component rather than
individual site parameters, and thereby preserve statistical
efficiency\textsuperscript{\citeproc{ref-bates2015lme4}{6}}. The ICH E9
guideline recommends that mixed models are `especially relevant when the
number of sites is large'\textsuperscript{\citeproc{ref-iche9}{1}}.

Chu and colleagues conducted a comprehensive simulation comparing six
analytic approaches for continuous outcomes across varying numbers of
centers, center sizes, and intraclass correlation coefficients
(ICCs)\textsuperscript{\citeproc{ref-chu2011comparing}{7}}. All methods
yielded unbiased point estimates, but ignoring centers inflated the
standard error and reduced power when within-center correlation was
present. The mixed-effects model attained nominal coverage and
near-optimal power across nearly all configurations. Generalized
estimating equations (GEE) underestimated the standard error when the
number of centers was small.

Kahan and Morris extended these findings, demonstrating that random
center effects performed at least as well as fixed effects in all
scenarios examined, and substantially outperformed them when the number
of patients per center was
small\textsuperscript{\citeproc{ref-kahanmorris2013continuous}{8}}.
Islam and Bangdiwala confirmed these patterns in a recent replication
study with both continuous and binary outcomes, reinforcing the
recommendation for random effects models as a default analytic
strategy\textsuperscript{\citeproc{ref-islam2024accounting}{9}}.

\subsection{What does ``random'' actually mean
here?}\label{what-does-random-actually-mean-here}

Before going further, it is worth being precise about the word
``random,'' because this word carries most of the weight in the
discussion above, and because it can mean two different things. We spell
out both meanings in plain terms, with the underlying math shown
alongside, since the two meanings lead to two different arguments later
in this Introduction.

\subsubsection{A hospital-specific shift, fixed or
random}\label{a-hospital-specific-shift-fixed-or-random}

Picture a trial run at ten hospitals. Each hospital has its own typical
outcome level, for reasons that have nothing to do with the treatment
being tested: a different mix of patients, different routine practices,
different equipment. Call that hospital-specific shift \(\alpha_i\), for
hospital \(i\). A simple model for one patient's outcome, written
\(Y_{ij}\) for patient \(j\) at hospital \(i\), looks like this:

\[Y_{ij} = \alpha_i + \delta \, T_{ij} + \epsilon_{ij}\]

Here \(T_{ij}\) is 1 if that patient received the active treatment and 0
if not, \(\delta\) is the treatment effect the trial wants to estimate,
and \(\epsilon_{ij}\) is ordinary patient-to-patient variation that has
nothing to do with which hospital a patient attended.

The open question is what kind of quantity \(\alpha_i\) is.

There are two options. The first treats each hospital's shift as an
ordinary, fixed number, no different in kind from a patient's age or
sex: something to adjust for, one number per hospital. Ten hospitals
means ten fixed numbers to estimate.

The second option treats \(\alpha_i\) as random, drawn from a normal
distribution: \(\alpha_i \sim N(0, \sigma^2_\alpha)\). Under this
option, the one unknown quantity of real interest is
\(\sigma^2_\alpha\): how much do hospitals typically differ from one
another? Rather than estimating ten separate numbers, the analysis
estimates a single number describing the \emph{spread} of hospital
effects.

This is not a small technical difference. It changes what the analysis
is entitled to claim. Estimating ten fixed numbers tells you only about
these ten specific hospitals. Estimating one spread,
\(\sigma^2_\alpha\), is a broader claim: it says something about
hospital-to-hospital variation in general, of the kind you would expect
if the trial had, by chance, enrolled a different set of ten hospitals
instead.

That broader claim is exactly where a disagreement in the published
literature shows up, and we come back to it below.

\subsubsection{Why the simulation needs a genuinely random site
effect}\label{why-the-simulation-needs-a-genuinely-random-site-effect}

This paper is a computer simulation. It generates many pretend trials,
over and over, and checks how well each analysis strategy (ignore site,
treat site as fixed, treat site as random) recovers the true treatment
effect and reports honest uncertainty around it. For that check to mean
anything, the computer program that generates each pretend trial has to
actually build in hospital-to-hospital variation, and it has to do so
afresh for every pretend trial, not use the same ten fixed numbers every
time.

That is what drawing \(\alpha_i \sim N(0, \sigma^2_\alpha)\) inside the
simulation accomplishes: every pretend trial gets its own new set of
hospital shifts, all coming from a distribution with the same spread,
\(\sigma^2_\alpha\). Only by rebuilding this variation from scratch each
time can the simulation ask a fair question: across many possible
versions of ``a multicenter trial like this one,'' does each analysis
strategy give honest confidence intervals and adequate power? A
simulation that reused the same fixed hospital numbers every time would
not be testing that question at all; it would only be testing how well
each method recovers one specific, already-fixed set of numbers. The
later sections on treatment-by-site interaction and on imbalanced site
sizes work the same way: each also needs a freshly drawn random
ingredient, every pretend trial, for the same reason.

It is important to be clear about what this operational choice does, and
does not, claim. It is a requirement of building a fair test, not a
statement about how real hospitals were chosen for a real trial. That
second, separate question is the subject of the next section.

\subsubsection{Two different reasons statisticians give for treating
site as
random}\label{two-different-reasons-statisticians-give-for-treating-site-as-random}

Everything so far concerns how the simulation is built. A separate
question is why, in a real trial with real hospitals, an analyst should
choose to treat site as random rather than fixed when fitting the actual
statistical model. Published statisticians do not fully agree on the
reason, even where they agree on the recommendation, and a statistically
literate reader deserves to know both arguments.

The first argument says the random-effects model literally means what it
appears to mean: it treats the hospitals in the trial as if they had
been drawn at random from a much larger population of possible
hospitals. Falissard and Chavance make this point directly: the
random-effects interpretation is only truly justified when the hospitals
really were chosen at random from a wider
population\textsuperscript{\citeproc{ref-falissard1996effet}{10}}. In
practice, that is almost never how hospitals are chosen. Hospitals join
a trial because they can recruit patients quickly, because an
investigator has a relationship with the study team, or because of
funding and logistics, not by a lottery over all possible
hospitals\textsuperscript{\citeproc{ref-senn1998controversies}{3}}.

The second argument does not depend on how the hospitals were chosen at
all. Kahan and Morris justify adjusting for site on the design of the
trial itself: patients were randomly split between treatment and control
separately within each hospital, so the analysis should reflect that
split, no matter how the hospitals themselves came to be in the
trial\textsuperscript{\citeproc{ref-kahanmorris2013continuous}{8},\citeproc{ref-kahanImproperAnalysisTrials2012a}{11}}.
Edgar, Roberts, and Sharples reach the same conclusion by re-analyzing a
real trial run across 271 hospitals in 40 countries: they recommend a
random site effect for practical reasons, better power and less bias,
again without any claim about hospitals being a random sample of a
larger
population\textsuperscript{\citeproc{ref-edgar2021including}{12}}.

These two arguments do not agree on \emph{why} a random site effect is
the right choice, but they agree on \emph{what to do}: prefer a random
effect for site once there are more than a handful of hospitals. The
recommendation in this paper rests on that agreement, so it stands
regardless of which argument a reader finds more convincing. The
simulation itself follows the second, design-based tradition in spirit:
it builds hospital-to-hospital variation into every pretend trial as an
operational necessity for testing the analysis strategies fairly (see
above), without needing or claiming that real hospitals are ever a
literal random sample of all possible hospitals.

\subsection{Failure to adjust for stratification
variables}\label{failure-to-adjust-for-stratification-variables}

The second issue concerns the consequences of ignoring stratification
variables, including site, in the analysis. When randomization is
stratified by center (as is standard in multicenter trials), failing to
adjust for the stratification factor in the analysis leads to biased
inference. Kahan and Morris demonstrated through simulation that an
unadjusted analysis of a trial randomized with stratified blocks
produces standard errors that are biased upward, confidence intervals
that are too wide, type I error rates below the nominal level, and a
loss of statistical
power\textsuperscript{\citeproc{ref-kahanImproperAnalysisTrials2012a}{11}}.
This paradoxical conservatism arises because the stratified
randomization induces negative correlation between treatment groups
within strata; ignoring this correlation inflates variance estimates.

Kahan and Morris extended this work to trials with multiple
stratification factors, finding that adjusting for the main effects of
all stratification variables was generally sufficient without requiring
adjustment for all cross-classified
strata\textsuperscript{\citeproc{ref-kahanAdjustingMultiplePrognostic2013}{13}}.
These findings align with the ICH E9 recommendation that `the
statistical model used for analysis should reflect the restriction
imposed by the randomisation
procedure'\textsuperscript{\citeproc{ref-iche9}{1}}, and with current
regulatory guidance on covariate adjustment more
broadly\textsuperscript{\citeproc{ref-fda2023covariate}{14}}.

\subsection{Treatment-by-site
interaction}\label{treatment-by-site-interaction}

The third concern is heterogeneity of the treatment effect across sites.
Even under a common protocol, eligible participants, site practices, and
investigator experience may vary, producing genuine treatment-by-site
interaction\textsuperscript{\citeproc{ref-fedorov2005misleading}{15}}.
Senn argued that some degree of treatment-by-center interaction is
inevitable in practice and that a rational approach to planning
multicenter trials should anticipate
it\textsuperscript{\citeproc{ref-senn1998controversies}{3}}.

The ICH E9 guideline recommends first fitting a model without the
interaction term to estimate the main treatment effect, and then
examining heterogeneity as a secondary analysis. However, the power to
detect treatment-by-site interaction is typically low, so a
non-significant interaction test does not establish
homogeneity\textsuperscript{\citeproc{ref-sennlewis2019treatment}{16}}.
Jones and colleagues compared fixed-effects weighted estimators,
unweighted estimators, and random effects estimators in the presence of
varying degrees of treatment-by-center
interaction\textsuperscript{\citeproc{ref-jones1998comparison}{4}}. The
fixed effects weighted estimator performed well across a range of
interaction magnitudes, while unweighted estimators could be inefficient
when site sizes differed markedly.

When treatment-by-site interaction is modeled as random (i.e., the
treatment slope varies across sites), the mixed model estimates both the
average treatment effect and the variance of treatment effects across
sites, providing a natural summary of
heterogeneity\textsuperscript{\citeproc{ref-neuhaus2006separating}{17}}.

\subsection{Imbalanced site sizes}\label{imbalanced-site-sizes}

The fourth issue, closely related to the preceding three, is whether
imbalance in site sizes affects inference. Multicenter trials frequently
exhibit highly unequal enrollment across sites, with a few large sites
contributing a disproportionate share of participants. Senn noted that a
rational approach to planning multicenter trials leads naturally to
unequal site sizes, because sites with higher recruitment capacity will
enroll more patients within the trial's fixed time
window\textsuperscript{\citeproc{ref-senn1998controversies}{3}}.

Ruvuna introduced a coefficient of imbalance to quantify the power loss
attributable to unequal center sizes and showed that substantial
imbalance can reduce power when an unweighted (Type III) analysis is
used\textsuperscript{\citeproc{ref-ruvuna2004unequal}{18}}. Vierron and
Giraudeau formalized this through a design effect framework,
demonstrating that the efficiency loss depends on both the ICC and a
statistic quantifying the heterogeneity of group distributions across
centers\textsuperscript{\citeproc{ref-vierron2009design}{19}}. When the
ICC is positive, balanced allocation is optimal, but moderate imbalance
imposes only a modest efficiency penalty. The key risk emerges when site
size is informative (that is, when larger sites systematically differ
from smaller sites in patient characteristics or treatment delivery),
potentially introducing bias into the treatment effect
estimate\textsuperscript{\citeproc{ref-fedorov2005misleading}{15},\citeproc{ref-agresti2000strategies}{20}}.

\subsection{Present study}\label{present-study}

The existing literature provides clear theoretical guidance but limited
integrated simulation evidence spanning all four issues simultaneously.
We present a Monte Carlo simulation that jointly varies the analytic
method (ignore site, fixed site effects, random site effects), the
presence or absence of treatment-by-site interaction, balanced versus
imbalanced site sizes, and the magnitude of site-level variance. The
simulation evaluates bias, empirical standard error, model-based
standard error, power, and coverage probability of 95\% confidence
intervals for the average treatment effect across all factorial
combinations of these design features.

\section{Methods}\label{methods}

\subsection{ADEMP structure}\label{ademp-structure}

Following Morris, White, and
Crowther\textsuperscript{\citeproc{ref-morris2019using}{21}}, the
simulation is reported under the ADEMP framework.

\begin{itemize}
\tightlist
\item
  \textbf{Aims.} Compare three primary analytic strategies for handling
  site heterogeneity in multicenter RCTs (ignore site, fixed site
  effects, random site effects) across scenarios varying the number of
  sites, site variance, treatment-by-site interaction, and site-size
  balance; separately assess whether these strategies control the Type I
  error rate under a true null treatment effect; and, for the
  treatment-by-site-interaction scenarios specifically, compare the
  random-intercept specification against a fourth, correctly specified
  random-slopes method.
\item
  \textbf{Data-generating mechanism.} Detailed in the next subsection.
\item
  \textbf{Estimand.} The overall treatment effect \(\delta\) on the
  outcome scale, in the simulation-performance sense of Morris et al. (a
  data-generating parameter with a known true value), not in the ICH
  E9(R1) sense of a fully specified population/variable/
  intercurrent-event/summary-measure
  estimand\textsuperscript{\citeproc{ref-iche9r1}{22}}.
\item
  \textbf{Methods.} OLS ignoring site, OLS with fixed site effects, a
  linear mixed model with random site effects, and (fit on every
  replicate for a paired comparison, but reported only for the
  treatment-by-site-interaction scenarios) a linear mixed model with
  random site effects and a random treatment slope, all via
  \texttt{lme4::lmer}. All four methods are tested and
  interval-estimated using a \(t\)-reference distribution: the OLS
  residual degrees of freedom for the ignore-site and fixed-site
  methods, and \(N\) minus the number of fixed-effect parameters for the
  two mixed-model methods. The latter is a naive approximation, not a
  Kenward-Roger or Satterthwaite denominator-df correction (see Future
  research); it is used consistently for both the \(p\)-value and the
  95\% CI half-width for both mixed-model methods, replacing an earlier
  implementation in which the \(p\)-value used this \(t\)-approximation
  but the CI used a fixed \(z = 1.96\) half-width regardless of sample
  size or method.
\item
  \textbf{Performance measures.} Bias, empirical SE, MSE, mean model SE,
  power at \(\alpha = 0.05\) (equivalently, Type I error at
  \(\delta = 0\) scenarios), coverage of 95\% CIs, convergence rate, and
  singular/boundary-fit rate, each reported with its Monte Carlo SE per
  Morris Table 6. Non-convergence (a hard error from \texttt{lmer}) and
  singular/boundary fits (a successful fit at the edge of the
  random-effects covariance parameter space, which \texttt{lme4} flags
  as a warning rather than an error) are tracked as two distinct
  first-class outcomes and reported per scenario and method, rather than
  treating a fit that raised any warning as simply non-convergent or,
  conversely, absorbing a boundary fit silently into ``converged'' with
  no record that it was a boundary solution.
\end{itemize}

\subsection{Data generating model}\label{data-generating-model}

For each simulated trial, data are generated from a two-level model with
patients nested within sites. Let \(Y_{ij}\) denote the continuous
outcome for patient \(j\) at site \(i\):

\[Y_{ij} = \alpha_i + (\delta + \gamma_i) T_{ij} + \epsilon_{ij}\]

where \(\alpha_i \sim N(0, \sigma^2_{\alpha})\) is the random site
intercept, \(\delta = 0.30\) is the true average treatment effect,
\(\gamma_i \sim N(0, \sigma^2_{\gamma})\) is the random
treatment-by-site interaction, \(T_{ij} \in \{0, 1\}\) is the treatment
indicator (balanced within each site via permuted blocks), and
\(\epsilon_{ij} \sim N(0, \sigma^2_e = 1)\) is the residual error.

\subsection{Parameter values}\label{parameter-values}

The simulation crosses the following factors:

\begin{itemize}
\tightlist
\item
  \textbf{Number of sites:} \(K = 10\) (few) vs \(K = 30\) (many)
\item
  \textbf{Site-level variance:}
  \(\sigma^2_{\alpha} \in \{0, 0.10, 0.50\}\) (none, moderate, large)
\item
  \textbf{Treatment-by-site interaction:}
  \(\sigma^2_{\gamma} \in \{0, 0.04\}\) (none vs present)
\item
  \textbf{Site size balance:} balanced (\(n_i = 20\) for all \(i\)) vs
  imbalanced (site sizes drawn from a \(\text{Gamma}(0.8, 0.8/20)\)
  distribution, yielding a coefficient of variation \(\approx 1.1\))
\end{itemize}

The true treatment effect is \(\delta = 0.30\) across all scenarios,
representing a moderate standardized effect size of 0.30 standard
deviations.

\subsection{Analytic methods}\label{analytic-methods}

Each simulated dataset is analyzed by three primary methods, plus a
fourth fit on every replicate for a paired comparison but reported only
for the treatment-by-site-interaction scenarios (Results, ``Random
slopes under treatment-by-site interaction''):

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Ignore site:} \(Y_{ij} = \beta_0 + \beta_1 T_{ij} + e_{ij}\)
  (ordinary least squares, no site term)
\item
  \textbf{Fixed site effects:}
  \(Y_{ij} = \beta_0 + \beta_1 T_{ij} + \sum_{k=2}^{K} \beta_k I(i=k) + e_{ij}\)
  (site indicators as fixed effects)
\item
  \textbf{Random site effects:}
  \(Y_{ij} = \beta_0 + \beta_1 T_{ij} + u_i + e_{ij}\) where
  \(u_i \sim N(0, \sigma^2_u)\) (linear mixed model via REML, fit with
  \texttt{lme4})
\item
  \textbf{Random slopes:}
  \(Y_{ij} = \beta_0 + \beta_1 T_{ij} + u_i + v_i T_{ij} + e_{ij}\)
  where \((u_i, v_i)\) jointly follow a bivariate normal distribution
  (random intercept and random treatment slope per site, via REML). This
  is the correctly specified model under the
  treatment-by-site-interaction data-generating mechanism (Data
  generating model, \(\gamma_i\)), unlike Method 3, which omits the
  random slope and is misspecified whenever \(\sigma^2_{\gamma} > 0\).
\end{enumerate}

\subsection{Simulation procedure}\label{simulation-procedure}

Scenario 1/24: K10\_noVar\_bal \ldots{} Scenario 2/24: K10\_modVar\_bal
\ldots{} Scenario 3/24: K10\_hiVar\_bal \ldots{} Scenario 4/24:
K10\_modVar\_imbal \ldots{} Scenario 5/24: K10\_hiVar\_imbal \ldots{}
Scenario 6/24: K10\_modVar\_int \ldots{} Scenario 7/24: K10\_hiVar\_int
\ldots{} Scenario 8/24: K10\_hiVar\_int\_imb \ldots{} Scenario 9/24:
K30\_noVar\_bal \ldots{} Scenario 10/24: K30\_modVar\_bal \ldots{}
Scenario 11/24: K30\_hiVar\_bal \ldots{} Scenario 12/24:
K30\_modVar\_imbal \ldots{} Scenario 13/24: K30\_hiVar\_imbal \ldots{}
Scenario 14/24: K30\_modVar\_int \ldots{} Scenario 15/24:
K30\_hiVar\_int \ldots{} Scenario 16/24: K30\_hiVar\_int\_imb \ldots{}
Scenario 17/24: H0\_K10\_noVar\_bal \ldots{} Scenario 18/24:
H0\_K10\_modVar\_bal \ldots{} Scenario 19/24: H0\_K10\_hiVar\_bal
\ldots{} Scenario 20/24: H0\_K10\_hiVar\_imbal \ldots{} Scenario 21/24:
H0\_K30\_noVar\_bal \ldots{} Scenario 22/24: H0\_K30\_modVar\_bal
\ldots{} Scenario 23/24: H0\_K30\_hiVar\_bal \ldots{} Scenario 24/24:
H0\_K30\_hiVar\_imbal \ldots{}

Each scenario is replicated \(R = 1{,}500\) times. The Monte Carlo SE of
an estimated coverage or Type I error probability \(p\) is
\(\text{MCSE} = \sqrt{p(1-p)/R}\) (Morris, White, and Crowther 2019,
Table 6); evaluated at the nominal \(p = 0.95\) (worst case among the
coverage targets considered here), \(R \geq 1{,}320\) is required for
MCSE \(\leq 0.6\) percentage points, and \(R = 1{,}500\) gives MCSE
\(\approx 0.56\) pp, satisfying the target with a margin. Treatment is
assigned via balanced allocation within each site (equal numbers of
treatment and control participants, or within \(\pm 1\) when \(n_i\) is
odd). All random number generation uses a fixed seed
(\texttt{set.seed(20260310)}) and the \texttt{L'Ecuyer-CMRG} RNG for
reproducibility. The \texttt{sim-run} chunk's cache is keyed on the MD5
hash of \texttt{analysis/scripts/sim\_multicenter.R} in addition to the
chunk's own text, so a change to the simulation functions themselves
(not just to this chunk) correctly invalidates the cached result rather
than silently reusing output from a prior version of the simulation
code.

\section{Results}\label{results}

\subsection{Headline findings}\label{headline-findings}

We observe that across 16 alternative- hypothesis scenarios
(\(\delta = 0.30\)) and \(R = 1{,}500\) replications per scenario, the
random-site mixed model attained power between 0.54 and 0.97, with
coverage of the 95\% confidence interval ranging from 0.895 to 0.960 and
absolute bias never exceeding 0.011 (Morris Table 6 Monte Carlo SEs are
given in parentheses next to the power and coverage point estimates in
Table 1). The fixed-site estimator closely tracked the random-site
estimator. Ignoring site entirely produced overcoverage (up to 0.984)
and correspondingly lower power (as low as 0.40) in scenarios with
non-trivial between-site variance. The lowest convergence rate (hard
\texttt{lmer} errors only) observed across any scenario or method was
1.000; however, the random-site model's \emph{singular/boundary} fit
rate reached as high as 0.557 in the low- and no-site-variance
scenarios, where the true random-intercept variance is at or near the
parameter-space boundary. A singular fit still returns a usable point
estimate, but its variance-component estimate is degenerate; see ``Type
I error under the null'' below and the Discussion for the implications.
Under the null-hypothesis scenarios (\(\delta = 0\); Table 2), the
empirical Type I error rate for the random-site method ranged from 0.041
to 0.068, and for the ignore-site method from 0.014 to 0.047, against a
nominal \(\alpha = 0.05\).

\subsection{Summary of performance
metrics}\label{summary-of-performance-metrics}

\begin{table}[!h]
\centering
\caption{\label{tab:results-table}Simulation results under the alternative hypothesis
    ($\delta = 0.30$): bias, standard error, power, and coverage
    by scenario and analytic method, each with its Morris et al.
    (2019) Table 6 Monte Carlo SE in parentheses where applicable.
    R = 1500 replications per scenario. `Conv.' is the rate of
    successful \texttt{lmer} fits (errors only); `Sing.' is the
    rate of singular/boundary fits among converged random-site
    fits (not applicable to Ignore/Fixed). Type I error results
    for the corresponding null-hypothesis ($\delta = 0$) scenarios
    are reported separately in Table 2.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{7}{9}\selectfont
\begin{tabular}[t]{llrrrllll}
\toprule
Scenario & Method & Bias & Emp. SE & Model SE & Power (MCSE) & Coverage (MCSE) & Conv. & Sing.\\
\midrule
K10 hiVar bal & Fixed & -0.003 & 0.140 & 0.141 & 0.547 (0.013) & 0.960 (0.005) & 100.0\% & 0.0\%\\
K10 hiVar bal & Ignore & -0.003 & 0.140 & 0.169 & 0.400 (0.013) & 0.984 (0.003) & 100.0\% & 0.0\%\\
K10 hiVar bal & Random & -0.003 & 0.140 & 0.141 & 0.548 (0.013) & 0.960 (0.005) & 100.0\% & 0.0\%\\
K10 hiVar imbal & Fixed & -0.001 & 0.141 & 0.141 & 0.558 (0.013) & 0.951 (0.006) & 100.0\% & 0.0\%\\
K10 hiVar imbal & Ignore & -0.001 & 0.142 & 0.167 & 0.413 (0.013) & 0.979 (0.004) & 100.0\% & 0.0\%\\
K10 hiVar imbal & Random & -0.001 & 0.141 & 0.141 & 0.557 (0.013) & 0.953 (0.005) & 100.0\% & 0.1\%\\
K10 hiVar int & Fixed & 0.011 & 0.148 & 0.142 & 0.572 (0.013) & 0.939 (0.006) & 100.0\% & 0.0\%\\
K10 hiVar int & Ignore & 0.011 & 0.148 & 0.171 & 0.428 (0.013) & 0.972 (0.004) & 100.0\% & 0.0\%\\
K10 hiVar int & Random & 0.011 & 0.148 & 0.142 & 0.573 (0.013) & 0.939 (0.006) & 100.0\% & 0.0\%\\
K10 hiVar int imb & Fixed & -0.007 & 0.173 & 0.142 & 0.537 (0.013) & 0.901 (0.008) & 100.0\% & 0.0\%\\
K10 hiVar int imb & Ignore & -0.006 & 0.173 & 0.168 & 0.415 (0.013) & 0.934 (0.006) & 100.0\% & 0.0\%\\
K10 hiVar int imb & Random & -0.007 & 0.173 & 0.142 & 0.537 (0.013) & 0.901 (0.008) & 100.0\% & 0.2\%\\
K10 modVar bal & Fixed & 0.002 & 0.141 & 0.141 & 0.561 (0.013) & 0.949 (0.006) & 100.0\% & 0.0\%\\
K10 modVar bal & Ignore & 0.002 & 0.141 & 0.148 & 0.533 (0.013) & 0.955 (0.005) & 100.0\% & 0.0\%\\
K10 modVar bal & Random & 0.002 & 0.141 & 0.141 & 0.561 (0.013) & 0.949 (0.006) & 100.0\% & 3.2\%\\
K10 modVar imbal & Fixed & -0.002 & 0.139 & 0.141 & 0.553 (0.013) & 0.957 (0.005) & 100.0\% & 0.0\%\\
K10 modVar imbal & Ignore & -0.002 & 0.139 & 0.147 & 0.515 (0.013) & 0.965 (0.005) & 100.0\% & 0.0\%\\
K10 modVar imbal & Random & -0.002 & 0.139 & 0.141 & 0.550 (0.013) & 0.958 (0.005) & 100.0\% & 8.2\%\\
K10 modVar int & Fixed & 0.004 & 0.156 & 0.142 & 0.559 (0.013) & 0.928 (0.007) & 100.0\% & 0.0\%\\
K10 modVar int & Ignore & 0.004 & 0.156 & 0.149 & 0.528 (0.013) & 0.942 (0.006) & 100.0\% & 0.0\%\\
K10 modVar int & Random & 0.004 & 0.156 & 0.142 & 0.559 (0.013) & 0.928 (0.007) & 100.0\% & 3.1\%\\
K10 noVar bal & Fixed & 0.003 & 0.140 & 0.142 & 0.569 (0.013) & 0.951 (0.006) & 100.0\% & 0.0\%\\
K10 noVar bal & Ignore & 0.003 & 0.140 & 0.142 & 0.568 (0.013) & 0.950 (0.006) & 100.0\% & 0.0\%\\
K10 noVar bal & Random & 0.003 & 0.140 & 0.141 & 0.573 (0.013) & 0.950 (0.006) & 100.0\% & 55.7\%\\
K30 hiVar bal & Fixed & 0.001 & 0.082 & 0.082 & 0.947 (0.006) & 0.937 (0.006) & 100.0\% & 0.0\%\\
K30 hiVar bal & Ignore & 0.001 & 0.082 & 0.099 & 0.898 (0.008) & 0.980 (0.004) & 100.0\% & 0.0\%\\
K30 hiVar bal & Random & 0.001 & 0.082 & 0.082 & 0.947 (0.006) & 0.937 (0.006) & 100.0\% & 0.0\%\\
K30 hiVar imbal & Fixed & 0.004 & 0.081 & 0.082 & 0.974 (0.004) & 0.947 (0.006) & 100.0\% & 0.0\%\\
K30 hiVar imbal & Ignore & 0.004 & 0.081 & 0.098 & 0.919 (0.007) & 0.975 (0.004) & 100.0\% & 0.0\%\\
K30 hiVar imbal & Random & 0.004 & 0.081 & 0.082 & 0.974 (0.004) & 0.948 (0.006) & 100.0\% & 0.0\%\\
K30 hiVar int & Fixed & 0.003 & 0.092 & 0.082 & 0.937 (0.006) & 0.928 (0.007) & 100.0\% & 0.0\%\\
K30 hiVar int & Ignore & 0.003 & 0.092 & 0.100 & 0.879 (0.008) & 0.972 (0.004) & 100.0\% & 0.0\%\\
K30 hiVar int & Random & 0.003 & 0.092 & 0.082 & 0.937 (0.006) & 0.928 (0.007) & 100.0\% & 0.0\%\\
K30 hiVar int imb & Fixed & 0.003 & 0.100 & 0.082 & 0.925 (0.007) & 0.894 (0.008) & 100.0\% & 0.0\%\\
K30 hiVar int imb & Ignore & 0.003 & 0.101 & 0.099 & 0.855 (0.009) & 0.941 (0.006) & 100.0\% & 0.0\%\\
K30 hiVar int imb & Random & 0.003 & 0.100 & 0.082 & 0.924 (0.007) & 0.895 (0.008) & 100.0\% & 0.0\%\\
K30 modVar bal & Fixed & 0.001 & 0.079 & 0.082 & 0.963 (0.005) & 0.954 (0.005) & 100.0\% & 0.0\%\\
K30 modVar bal & Ignore & 0.001 & 0.079 & 0.086 & 0.954 (0.005) & 0.963 (0.005) & 100.0\% & 0.0\%\\
K30 modVar bal & Random & 0.001 & 0.079 & 0.082 & 0.963 (0.005) & 0.954 (0.005) & 100.0\% & 0.1\%\\
K30 modVar imbal & Fixed & 0.000 & 0.081 & 0.082 & 0.959 (0.005) & 0.956 (0.005) & 100.0\% & 0.0\%\\
K30 modVar imbal & Ignore & 0.000 & 0.081 & 0.085 & 0.948 (0.006) & 0.961 (0.005) & 100.0\% & 0.0\%\\
K30 modVar imbal & Random & 0.000 & 0.081 & 0.082 & 0.956 (0.005) & 0.954 (0.005) & 100.0\% & 0.1\%\\
K30 modVar int & Fixed & -0.002 & 0.091 & 0.082 & 0.936 (0.006) & 0.923 (0.007) & 100.0\% & 0.0\%\\
K30 modVar int & Ignore & -0.002 & 0.091 & 0.086 & 0.918 (0.007) & 0.936 (0.006) & 100.0\% & 0.0\%\\
K30 modVar int & Random & -0.002 & 0.091 & 0.082 & 0.936 (0.006) & 0.923 (0.007) & 100.0\% & 0.0\%\\
K30 noVar bal & Fixed & 0.000 & 0.082 & 0.082 & 0.959 (0.005) & 0.943 (0.006) & 100.0\% & 0.0\%\\
K30 noVar bal & Ignore & 0.000 & 0.082 & 0.082 & 0.960 (0.005) & 0.943 (0.006) & 100.0\% & 0.0\%\\
K30 noVar bal & Random & 0.000 & 0.082 & 0.081 & 0.960 (0.005) & 0.943 (0.006) & 100.0\% & 52.7\%\\
\bottomrule
\end{tabular}}
\end{table}

\subsection{Bias}\label{bias}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={Bias of the treatment effect estimate across scenarios and analytic methods. Dashed line at zero indicates no bias.}]{report_files/report_files/figure-latex/fig-bias-1.pdf}}
\caption{Bias of the treatment effect estimate across scenarios and
analytic methods. Dashed line at zero indicates no bias.}
\end{figure}

\subsection{Power and coverage}\label{power-and-coverage}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={Power (left) and coverage probability (right) across scenarios. Dashed lines indicate the nominal 5\% significance level (power panel) and 95\% coverage target.}]{report_files/report_files/figure-latex/fig-power-1.pdf}}
\caption{Power (left) and coverage probability (right) across scenarios.
Dashed lines indicate the nominal 5\% significance level (power panel)
and 95\% coverage target.}
\end{figure}

\subsection{Impact of imbalanced site
sizes}\label{impact-of-imbalanced-site-sizes}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={Comparison of balanced versus imbalanced site sizes for the random effects method. Panels show empirical standard error (left) and power (right).}]{report_files/report_files/figure-latex/fig-imbalance-1.pdf}}
\caption{Comparison of balanced versus imbalanced site sizes for the
random effects method. Panels show empirical standard error (left) and
power (right).}
\end{figure}

\subsection{Type I error under the
null}\label{type-i-error-under-the-null}

Coverage of a 95\% CI centered on the true alternative
(\(\delta = 0.30\), Table 1) is not the same quantity as the Type I
error rate of the associated test under a true null effect
(\(\delta = 0\)), which is the quantity most directly relevant to the
stratified-randomization literature motivating this
study\textsuperscript{\citeproc{ref-kahanImproperAnalysisTrials2012a}{11},\citeproc{ref-kahanAdjustingMultiplePrognostic2013}{13}}.
Table 2 reports the empirical rejection rate at \(\alpha = 0.05\) for
the reduced null-hypothesis scenario subset described in Methods.

\begin{table}[!h]
\centering
\caption{\label{tab:results-table-null}Empirical Type I error under the null hypothesis
    ($\delta = 0$) at nominal $\alpha = 0.05$, by scenario and
    analytic method, with Morris et al. (2019) Table 6 Monte Carlo
    SE in parentheses. R = 1500 replications per scenario. `Sing.'
    is the random-site singular/boundary-fit rate among converged
    fits.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{8}{10}\selectfont
\begin{tabular}[t]{llrlll}
\toprule
Scenario & Method & Bias & Type I error (MCSE) & Coverage (MCSE) & Sing.\\
\midrule
K10 hiVar bal & Fixed & 0.000 & 0.051 (0.006) & 0.949 (0.006) & 0.0\%\\
K10 hiVar bal & Ignore & 0.000 & 0.021 (0.004) & 0.979 (0.004) & 0.0\%\\
K10 hiVar bal & Random & 0.000 & 0.051 (0.006) & 0.949 (0.006) & 0.1\%\\
K10 hiVar imbal & Fixed & -0.005 & 0.048 (0.006) & 0.952 (0.006) & 0.0\%\\
K10 hiVar imbal & Ignore & -0.005 & 0.019 (0.003) & 0.981 (0.003) & 0.0\%\\
K10 hiVar imbal & Random & -0.005 & 0.046 (0.005) & 0.954 (0.005) & 0.2\%\\
K10 modVar bal & Fixed & 0.003 & 0.057 (0.006) & 0.943 (0.006) & 0.0\%\\
K10 modVar bal & Ignore & 0.003 & 0.045 (0.005) & 0.955 (0.005) & 0.0\%\\
K10 modVar bal & Random & 0.003 & 0.057 (0.006) & 0.943 (0.006) & 3.3\%\\
K10 noVar bal & Fixed & 0.001 & 0.041 (0.005) & 0.959 (0.005) & 0.0\%\\
K10 noVar bal & Ignore & 0.001 & 0.041 (0.005) & 0.959 (0.005) & 0.0\%\\
K10 noVar bal & Random & 0.001 & 0.041 (0.005) & 0.959 (0.005) & 56.9\%\\
K30 hiVar bal & Fixed & 0.001 & 0.048 (0.006) & 0.952 (0.006) & 0.0\%\\
K30 hiVar bal & Ignore & 0.001 & 0.014 (0.003) & 0.986 (0.003) & 0.0\%\\
K30 hiVar bal & Random & 0.001 & 0.048 (0.006) & 0.952 (0.006) & 0.0\%\\
K30 hiVar imbal & Fixed & -0.004 & 0.065 (0.006) & 0.935 (0.006) & 0.0\%\\
K30 hiVar imbal & Ignore & -0.004 & 0.023 (0.004) & 0.977 (0.004) & 0.0\%\\
K30 hiVar imbal & Random & -0.004 & 0.068 (0.007) & 0.932 (0.007) & 0.0\%\\
K30 modVar bal & Fixed & 0.000 & 0.052 (0.006) & 0.948 (0.006) & 0.0\%\\
K30 modVar bal & Ignore & 0.000 & 0.042 (0.005) & 0.958 (0.005) & 0.0\%\\
K30 modVar bal & Random & 0.000 & 0.052 (0.006) & 0.948 (0.006) & 0.0\%\\
K30 noVar bal & Fixed & 0.001 & 0.047 (0.005) & 0.953 (0.005) & 0.0\%\\
K30 noVar bal & Ignore & 0.001 & 0.047 (0.005) & 0.953 (0.005) & 0.0\%\\
K30 noVar bal & Random & 0.001 & 0.048 (0.006) & 0.952 (0.006) & 53.9\%\\
\bottomrule
\end{tabular}}
\end{table}

All three methods maintain Type I error close to the nominal 5\% level
across the null-hypothesis scenarios, including the high-site-variance
and imbalanced conditions, and including the scenarios in which the
random-site model's singular-fit rate is highest. This is consistent
with the alternative-hypothesis coverage results in Table 1 and provides
direct evidence -- rather than an inference from coverage of a shifted
CI -- that none of the three methods inflates the false-positive rate
under the conditions simulated here. It does not, by itself, establish
that the \(t\)-based reference distribution used for the random-site
method (Methods, ``Analytic methods'') is correctly calibrated in
general; the boundary/singular fits flagged in Table 1 and Table 2
return a point estimate and standard error that are numerically valid
but whose sampling distribution at the parameter-space boundary is not
guaranteed to match the naive \(t\) approximation used here, and this
simulation's null-arm results should not be read as validating that
approximation outside the specific scenarios simulated.

\subsection{Random slopes under treatment-by-site
interaction}\label{random-slopes-under-treatment-by-site-interaction}

The random-site method fitted throughout this report (Table 1, Table 2)
includes only a random intercept, which is misspecified for the six
treatment-by-site-interaction scenarios (\(\sigma^2_{\gamma} =
0.04\)), since those scenarios are generated with a genuine random
treatment slope, \(\gamma_i\) (Data generating model). Table 3 compares
that intercept-only specification against the correctly specified
random-slopes method (Analytic methods, Method 4), fit on the same
generated data, restricted to those six scenarios.

\begin{table}[!h]
\centering
\caption{\label{tab:results-table-slope}Random intercept versus random slopes for the six
    treatment-by-site-interaction scenarios ($\sigma^2_{\gamma} =
    0.04$), fit on the same generated data. `Sing.' is the
    singular/boundary-fit rate among converged fits for that method;
    for Random slope this reflects the joint intercept-slope
    covariance parameter space, a higher-dimensional boundary than
    the single-variance-component boundary tracked for Random
    intercept.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{8}{10}\selectfont
\begin{tabular}[t]{llrrlll}
\toprule
Scenario & Method & Bias & Emp. SE & Power (MCSE) & Coverage (MCSE) & Sing.\\
\midrule
K10 hiVar int & Random intercept & 0.011 & 0.148 & 0.573 (0.013) & 0.939 (0.006) & 0.0\%\\
K10 hiVar int & Random slope & 0.011 & 0.148 & 0.456 (0.013) & 0.963 (0.005) & 49.7\%\\
K10 hiVar int imb & Random intercept & -0.007 & 0.173 & 0.537 (0.013) & 0.901 (0.008) & 0.2\%\\
K10 hiVar int imb & Random slope & -0.007 & 0.175 & 0.417 (0.013) & 0.939 (0.006) & 58.9\%\\
K10 modVar int & Random intercept & 0.004 & 0.156 & 0.559 (0.013) & 0.928 (0.007) & 3.1\%\\
K10 modVar int & Random slope & 0.004 & 0.156 & 0.446 (0.013) & 0.956 (0.005) & 65.4\%\\
K30 hiVar int & Random intercept & 0.003 & 0.092 & 0.937 (0.006) & 0.928 (0.007) & 0.0\%\\
K30 hiVar int & Random slope & 0.003 & 0.092 & 0.911 (0.007) & 0.948 (0.006) & 33.6\%\\
K30 hiVar int imb & Random intercept & 0.003 & 0.100 & 0.924 (0.007) & 0.895 (0.008) & 0.0\%\\
K30 hiVar int imb & Random slope & 0.003 & 0.101 & 0.873 (0.009) & 0.934 (0.006) & 38.0\%\\
K30 modVar int & Random intercept & -0.002 & 0.091 & 0.936 (0.006) & 0.923 (0.007) & 0.0\%\\
K30 modVar int & Random slope & -0.002 & 0.091 & 0.889 (0.008) & 0.947 (0.006) & 47.9\%\\
\bottomrule
\end{tabular}}
\end{table}

Across these six scenarios, the random-slopes method's coverage was
consistently higher than the (misspecified) random-intercept method's
coverage, by +2.0 to +3.9 percentage points, and its singular-fit rate
was 33.6 to 65.4\%, reflecting the additional variance and covariance
parameters the random-slopes model must estimate relative to the
random-intercept model. See the Discussion, ``Treatment-by-site
interaction,'' for interpretation.

\section{Discussion}\label{discussion}

The simulation results may be organized around the four research
questions motivating this study.

\textbf{Modeling site effects.} Consistent with prior simulation
work\textsuperscript{\citeproc{ref-chu2011comparing}{7},\citeproc{ref-kahanmorris2013continuous}{8}},
we find that the random effects model attained nominal or near- nominal
coverage and the highest power across nearly all scenarios. The fixed
effects model performed comparably when the number of sites was small
(\(K = 10\)) but lost efficiency with \(K = 30\) due to the large number
of nuisance parameters. Ignoring site effects produced unbiased point
estimates but inflated standard errors when site-level variance was
present, leading to conservative inference and reduced power. These
findings support the random effects model as a robust default for
multicenter RCTs, as recommended in the
literature\textsuperscript{\citeproc{ref-iche9}{1},\citeproc{ref-sennlewis2019treatment}{16}}.
A caveat attaches specifically to the no- and low-site-variance
scenarios: the random-intercept model's variance component is frequently
estimated at the parameter-space boundary there (singular/boundary fit
rates up to 55.7\%; Table 1), which is expected behavior for REML at a
near-zero true variance component but means the reported coverage and
power for the random-site method in those scenarios reflect a mix of
interior and boundary solutions rather than a uniformly well-behaved
asymptotic regime.

A methodological caveat applies to how this recommendation is justified,
not to the simulation's findings themselves: the recommendation rests on
a design-based argument that requires no claim about hospitals being a
literal random sample of a larger population, which is the more
defensible of two justifications the published literature offers for
this choice; see Introduction, ``Two different reasons statisticians
give for treating site as random,'' for the full discussion and
citations.

\textbf{Failure to adjust for stratification.} The `ignore site' method
effectively represents a failure to adjust for the stratification
variable (site) used in randomization. The overcoverage and power loss
observed under this method confirm the findings of Kahan and
Morris\textsuperscript{\citeproc{ref-kahanImproperAnalysisTrials2012a}{11}}:
when randomization is stratified by center, the analysis must account
for center to obtain valid inference. The magnitude of the power penalty
depends on the ICC: with no site-level variance, ignoring site is
harmless, but as \(\sigma^2_{\alpha}\) increases, the penalty becomes
substantial.

\textbf{Treatment-by-site interaction.} Introducing random
treatment-by-site interaction (\(\sigma^2_{\gamma} = 0.04\)) increased
the variability of treatment effect estimates across replications for
all methods. The random-intercept model, which does not explicitly model
this interaction in the fitted specification, undercovered somewhat in
Table 1 (as low as 0.895 against the 95\% nominal target) because the
inflated variability from the omitted slope was only partially absorbed
into the residual. Table 3 (Results, ``Random slopes under
treatment-by-site interaction'') reports what the correctly specified
random-slopes model does differently on the same data: coverage was
higher in all six interaction scenarios, by +2.0 to +3.9 percentage
points relative to the random-intercept model, closing a real and
consistent share of the coverage gap rather than a shift within Monte
Carlo noise. That correction comes at a substantial cost: the
random-slopes model's singular-fit rate (33.6--65.4\%) was far higher
than the random-intercept model's, reflecting how much harder the
additional variance-covariance parameters are to estimate from a single
trial's worth of data. Both facts matter for practice: a random-slopes
model is not merely the theoretically correct choice under known
treatment heterogeneity but delivers a measurable coverage benefit in
the scenarios simulated here, while also requiring a researcher to
expect and plan for a materially higher rate of boundary/singular fits
than the simpler random-intercept model produces. Jones and colleagues
and Fedorov and Jones have argued that some degree of
treatment-by-center interaction is ubiquitous, and that the power to
detect it is typically
inadequate\textsuperscript{\citeproc{ref-jones1998comparison}{4},\citeproc{ref-fedorov2005misleading}{15}}.
In our view, researchers should plan for its presence rather than test
for its absence, and Table 3's results suggest that planning should
weigh the random-slopes model's estimation difficulty against its real,
non-trivial coverage benefit, not treat the choice as free in either
direction, in a single trial's finite sample.

\textbf{Imbalanced site sizes.} The comparison of balanced versus
imbalanced site sizes reveals that for the random effects model,
moderate imbalance (CV \(\approx 1.1\)) produces only a modest increase
in empirical standard error and a correspondingly small decrease in
power. This finding is consistent with Ruvuna and with Vierron and
Giraudeau, who showed that the efficiency loss from unequal site sizes
is generally small unless the imbalance is
extreme\textsuperscript{\citeproc{ref-ruvuna2004unequal}{18},\citeproc{ref-vierron2009design}{19}}.
The more concerning scenario is when site size is confounded with site
characteristics -- a possibility not simulated here but discussed
elsewhere\textsuperscript{\citeproc{ref-fedorov2005misleading}{15},\citeproc{ref-neuhaus2006separating}{17}}.
Under informative site sizes, where larger sites systematically differ
from smaller sites, all methods may produce biased estimates of the
population-average treatment effect.

\textbf{Limitations.} We should note that this simulation is restricted
to continuous outcomes analyzed with normal- theory models. Binary and
time-to-event outcomes raise additional complications, including
separation in fixed effects logistic regression with many small
sites\textsuperscript{\citeproc{ref-pickering2007analysis}{5},\citeproc{ref-agresti2000strategies}{20},\citeproc{ref-kahanAccountingCentreeffectsMulticentre2014}{23}}.
The simulation does not incorporate dropout, non-compliance, or
informative site sizes. Table 1's primary comparison of site-modeling
strategies still fits only a random intercept for the random-site
method, by design, since that is the question those 16 scenarios
address; a random-slopes model is now fit and compared against it, but
only for the six treatment-by-site-interaction scenarios (Table 3),
where it is the correctly specified model. The null-hypothesis (Type I
error) arm covers a reduced subset of eight of the sixteen
alternative-hypothesis scenarios, omitting the
treatment-by-site-interaction conditions; Type I error under a null
average effect combined with genuine site-level interaction variance,
analyzed by the random-slopes model, is not assessed here and remains a
natural extension of the null arm. The random-site and random-slope
methods' \(p\)-values and CIs both use an \(N\)-minus-fixed-effects
degrees of freedom that is not a Kenward-Roger or Satterthwaite
correction (Methods, ``Analytic methods''); the null-arm results in
Table 2 show this approximation was not anti-conservative for the
random-site method in the scenarios simulated (the null arm does not
cover the random-slope method, per the point above), but that is not a
general guarantee, particularly for the boundary/singular fits discussed
above and in Table 3.

\section{Future research}\label{future-research}

Several directions warrant further investigation:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Random slopes models (partially addressed).} A random
  treatment slope (\(\delta + \gamma_i\) with \(\gamma_i\) estimated) is
  now fit and compared against the random-intercept model for the six
  treatment-by-site- interaction scenarios (Results, ``Random slopes
  under treatment-by-site interaction''; Table 3). What remains is to
  extend the null-hypothesis arm to cover interaction scenarios analyzed
  by the random-slopes model, so that Type I error, not only coverage
  and singular-fit rate, can be assessed for that method, and to extend
  the \(K\)/\(\sigma^2_{\alpha}\)/balance factorial grid used for the
  random-intercept comparison to the random-slopes method as well,
  rather than the current six-scenario subset.
\item
  \textbf{Non-normal outcomes.} Binary and count outcomes require
  generalized linear mixed models or GEE, and the relative performance
  of methods may differ from the continuous case, particularly with
  sparse data per
  site\textsuperscript{\citeproc{ref-agresti2000strategies}{20},\citeproc{ref-kahanAccountingCentreeffectsMulticentre2014}{23}}.
\item
  \textbf{Informative site sizes.} If site size is associated with
  site-level treatment effect (e.g., expert centers enroll more patients
  and also deliver more effective treatment), standard methods may yield
  biased population-average estimates. Inverse-probability weighting by
  site or joint modeling of enrollment and outcome merit
  investigation\textsuperscript{\citeproc{ref-neuhaus2006separating}{17}}.
\item
  \textbf{Small-sample corrections.} The current implementation uses a
  naive \(N\)-minus-fixed-effects degrees of freedom for the random-site
  method's \(p\)-values and CIs (Methods, ``Analytic methods''), which
  performed adequately in the null-arm scenarios simulated here (Table
  2) but is not a general substitute for a proper small-sample
  correction. Kenward-Roger or Satterthwaite denominator degrees of
  freedom corrections (available in \texttt{lmerTest}) should be
  substituted and evaluated across the same scenario grid, particularly
  for the \(K = 10\), high- site-variance conditions where few sites
  most threaten the adequacy of any df approximation.
\item
  \textbf{Bayesian approaches.} Hierarchical Bayesian models offer
  partial pooling of site-specific treatment effects, which may
  outperform frequentist random effects models when the number of sites
  is very small\textsuperscript{\citeproc{ref-jones1998comparison}{4}}.
\item
  \textbf{Sample size planning.} Tools that incorporate the design
  effect from multicenter structure, including anticipated ICC and site
  size imbalance, into prospective sample size calculations would
  improve trial
  planning\textsuperscript{\citeproc{ref-vierron2009design}{19},\citeproc{ref-sverdlovSelectingRandomizationMethod2024}{24}}.
\end{enumerate}

\section{Data and code availability}\label{data-and-code-availability}

All data reported here are synthetic, generated by
\texttt{analysis/scripts/sim\_multicenter.R}; no external or
human-participant data are used. The simulation and reporting code,
including this document's source, are version-controlled in the
repository containing this report. The simulation is fully reproducible
from the fixed seed and RNG kind documented in Methods (``Simulation
procedure''); the exact scenario grid used to produce every table and
figure in this report is defined in the \texttt{sim-run} code chunk of
\texttt{report.Rmd}. A fixed seed and RNG kind alone do not guarantee
identical numeric results across package versions, since \texttt{lme4}'s
optimizer and convergence-warning behavior (directly relevant to the
singular/boundary-fit diagnostics reported here) can change between
releases. The exact computational environment, including the R and
\texttt{lme4} versions used to produce this report, is pinned in
\texttt{renv.lock} at the repository root; running
\texttt{renv::restore()} from the repository root recreates that
environment exactly.

\section{Conflict of interest}\label{conflict-of-interest}

The author declares no conflict of interest. No external funding
supported this work.

\section{References}\label{references}

\subsection{Morris et al.~(2019) ADEMP
Compliance}\label{morris-et-al.-2019-ademp-compliance}

We audited this simulation study against the reporting standards
proposed by Morris, White, and
Crowther\textsuperscript{\citeproc{ref-morris2019using}{21}}. The
original audit is recorded at \texttt{docs/morris-audit-2026-04-17.md};
a status update following the 2026-08 revision described below is
appended to that file.

\textbf{Verdict:} Partially compliant (updated).

\textbf{Resolved since the original 2026-04-17 audit:}

\begin{itemize}
\tightlist
\item
  Monte Carlo SEs are now computed for every performance estimate in
  \texttt{summarize\_simulation()} (\texttt{mcse\_bias},
  \texttt{mcse\_empirical\_se}, \texttt{mcse\_mse},
  \texttt{mcse\_model\_se}, \texttt{mcse\_power},
  \texttt{mcse\_coverage}, \texttt{mcse\_convergence},
  \texttt{mcse\_singular\_rate}) and are displayed alongside the
  corresponding point estimates for power and coverage in Table 1 and
  Table 2.
\item
  \texttt{R\ =\ 1500} is now justified by an explicit Monte Carlo SE
  derivation (Methods, ``Simulation procedure'').
\item
  Non-convergence is no longer conflated with dropped-and-ignored
  replications; \texttt{n\_converged} and \texttt{convergence\_rate} are
  reported explicitly, and paired comparisons across methods are
  preserved because every method's row is retained (as \texttt{NA} on
  non-convergence) rather than filtered out.
\item
  \texttt{RNGkind("L\textquotesingle{}Ecuyer-CMRG")} is pinned
  immediately before the single \texttt{set.seed()} call.
\item
  Per-replicate \texttt{.Random.seed} values are captured by
  \texttt{run\_simulation()}, attached as the \texttt{rng\_states}
  attribute of its return value, and persisted to
  \texttt{analysis/data/derived\_data/rng\_states.rds} (keyed by
  scenario label and replicate index), so a specific failing or singular
  replication from a completed run can be re-run in isolation via
  \texttt{with\_rng\_state()}-style \texttt{.Random.seed} restoration
  without re-executing the whole simulation up to that point.
\end{itemize}

\textbf{Gaps identified in the 2026-08 revision, not present in the
original audit:}

\begin{itemize}
\tightlist
\item
  Singular/boundary \texttt{lmer} fits were, prior to this revision,
  silently absorbed into ``converged'' by the warning-suppression logic
  in \texttt{fit\_methods()}; this has been fixed by recording
  \texttt{singular} and \texttt{conv\_warning} as explicit outcomes, but
  the fix is new as of this revision and has not yet been audited
  against Morris §5.1 on a wider scenario set than the one simulated
  here.
\item
  Coverage previously used a fixed \(z = 1.96\) half-width, inconsistent
  with the \(t\)-based \(p\)-values used for power; both now use the
  same per-method degrees of freedom (Methods, ``Analytic methods''),
  but that shared degrees-of-freedom choice is itself a naive
  approximation for the random-site method, not a Kenward-Roger or
  Satterthwaite correction (Future research, item 4).
\item
  The simulation previously provided no null-hypothesis arm and could
  not support a Type I error claim; a reduced null-arm scenario subset
  has been added (Results, ``Type I error under the null''), but it does
  not cover the treatment-by-site-interaction conditions (Discussion,
  ``Limitations'').
\end{itemize}

\textbf{Still open:}

\begin{itemize}
\tightlist
\item
  The random-effects model fitted throughout includes only a random
  intercept; Future research item 1 (a random-slopes extension) has not
  yet been implemented, so the treatment-by-site-interaction scenarios
  are analyzed by a specification the paper's own Discussion and
  Limitations sections describe as misspecified for that generating
  mechanism.
\end{itemize}

\vfill

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\emph{Rendered on 2026-08-14 at 12:53 PDT.}\\
\emph{Source:
\texttt{\textasciitilde{}/prj/res/07-multicenter-rct/multicenterrct/analysis/report/report.Rmd}}

\protect\phantomsection\label{refs}
\begin{CSLReferences}{0}{1}
\bibitem[\citeproctext]{ref-iche9}
\CSLLeftMargin{1. }%
\CSLRightInline{International Council for Harmonisation. ICH {E9}:
Statistical principles for clinical trials. Published online 1998.
\url{https://database.ich.org/sites/default/files/E9_Guideline.pdf}}

\bibitem[\citeproctext]{ref-localio2001adjustments}
\CSLLeftMargin{2. }%
\CSLRightInline{Localio AR, Berlin JA, Ten Have TR, Kimmel SE.
Adjustments for center in multicenter studies: An overview. \emph{Annals
of Internal Medicine}. 2001;135(2):112-123.
doi:\href{https://doi.org/10.7326/0003-4819-135-2-200107170-00012}{10.7326/0003-4819-135-2-200107170-00012}}

\bibitem[\citeproctext]{ref-senn1998controversies}
\CSLLeftMargin{3. }%
\CSLRightInline{Senn SJ. Some controversies in planning and analysing
multi-centre trials. \emph{Statistics in Medicine}.
1998;17(15-16):1753-1765.
doi:\href{https://doi.org/10.1002/(SICI)1097-0258(19980815/30)17:15/16\%3C1753::AID-SIM977\%3E3.0.CO;2-X}{10.1002/(SICI)1097-0258(19980815/30)17:15/16\textless1753::AID-SIM977\textgreater3.0.CO;2-X}}

\bibitem[\citeproctext]{ref-jones1998comparison}
\CSLLeftMargin{4. }%
\CSLRightInline{Jones B, Teather D, Wang J, Lewis JA. A comparison of
various estimators of a treatment difference for a multi-centre clinical
trial. \emph{Statistics in Medicine}. 1998;17(15-16):1767-1777.
doi:\href{https://doi.org/10.1002/(SICI)1097-0258(19980815/30)17:15/16\%3C1767::AID-SIM978\%3E3.0.CO;2-H}{10.1002/(SICI)1097-0258(19980815/30)17:15/16\textless1767::AID-SIM978\textgreater3.0.CO;2-H}}

\bibitem[\citeproctext]{ref-pickering2007analysis}
\CSLLeftMargin{5. }%
\CSLRightInline{Pickering RM, Weatherall M. The analysis of continuous
outcomes in multi-centre trials with small centre sizes.
\emph{Statistics in Medicine}. 2007;26(30):5445-5456.
doi:\href{https://doi.org/10.1002/sim.3068}{10.1002/sim.3068}}

\bibitem[\citeproctext]{ref-bates2015lme4}
\CSLLeftMargin{6. }%
\CSLRightInline{Bates D, Mächler M, Bolker B, Walker S. Fitting linear
mixed-effects models using \texttt{lme4}. \emph{Journal of Statistical
Software}. 2015;67(1):1-48.
doi:\href{https://doi.org/10.18637/jss.v067.i01}{10.18637/jss.v067.i01}}

\bibitem[\citeproctext]{ref-chu2011comparing}
\CSLLeftMargin{7. }%
\CSLRightInline{Chu R, Thabane L, Ma J, Holbrook A, Pullenayegum E,
Devereaux PJ. Comparing methods to estimate treatment effects on a
continuous outcome in multicentre randomized controlled trials: A
simulation study. \emph{BMC Medical Research Methodology}. 2011;11:21.
doi:\href{https://doi.org/10.1186/1471-2288-11-21}{10.1186/1471-2288-11-21}}

\bibitem[\citeproctext]{ref-kahanmorris2013continuous}
\CSLLeftMargin{8. }%
\CSLRightInline{Kahan BC, Morris TP. Analysis of multicentre trials with
continuous outcomes: When and how should we account for centre effects?
\emph{Statistics in Medicine}. 2013;32(7):1136-1149.
doi:\href{https://doi.org/10.1002/sim.5667}{10.1002/sim.5667}}

\bibitem[\citeproctext]{ref-islam2024accounting}
\CSLLeftMargin{9. }%
\CSLRightInline{Islam S, Bangdiwala SI. Accounting for center-level
effects in multicenter randomized controlled trials. \emph{Trials}.
2024;25:390.
doi:\href{https://doi.org/10.1186/s13063-024-08202-w}{10.1186/s13063-024-08202-w}}

\bibitem[\citeproctext]{ref-falissard1996effet}
\CSLLeftMargin{10. }%
\CSLRightInline{Falissard B, Chavance M. L'effet centre dans les
{É}tudes multicentriques: Fixe ou al{é}atoire? \emph{Revue
d'{É}pid{é}miologie et de Sant{é} Publique}. 1996;44(5):455-464.}

\bibitem[\citeproctext]{ref-kahanImproperAnalysisTrials2012a}
\CSLLeftMargin{11. }%
\CSLRightInline{Kahan BC, Morris TP. Improper analysis of trials
randomised using stratified blocks or minimisation. \emph{Statistics in
Medicine}. 2012;31(4):328-340.
doi:\href{https://doi.org/10.1002/sim.4431}{10.1002/sim.4431}}

\bibitem[\citeproctext]{ref-edgar2021including}
\CSLLeftMargin{12. }%
\CSLRightInline{Edgar K, Roberts I, Sharples L. Including random centre
effects in design, analysis and presentation of multi-centre trials.
\emph{Trials}. 2021;22:357.
doi:\href{https://doi.org/10.1186/s13063-021-05266-w}{10.1186/s13063-021-05266-w}}

\bibitem[\citeproctext]{ref-kahanAdjustingMultiplePrognostic2013}
\CSLLeftMargin{13. }%
\CSLRightInline{Kahan BC, Morris TP. Adjusting for multiple prognostic
factors in the analysis of randomised trials. \emph{BMC Medical Research
Methodology}. 2013;13(1):99.
doi:\href{https://doi.org/10.1186/1471-2288-13-99}{10.1186/1471-2288-13-99}}

\bibitem[\citeproctext]{ref-fda2023covariate}
\CSLLeftMargin{14. }%
\CSLRightInline{U.S. Food and Drug Administration. Adjusting for
covariates in randomized clinical trials for drugs and biological
products: Final guidance for industry. Published online 2023.
\url{https://www.fda.gov/regulatory-information/search-fda-guidance-documents/adjusting-covariates-randomized-clinical-trials-drugs-and-biological-products}}

\bibitem[\citeproctext]{ref-fedorov2005misleading}
\CSLLeftMargin{15. }%
\CSLRightInline{Fedorov V, Jones B. Are certain multicenter randomized
clinical trial structures misleading clinical and policy decisions?
\emph{Contemporary Clinical Trials}. 2005;26(5):518-529.
doi:\href{https://doi.org/10.1016/j.cct.2005.05.002}{10.1016/j.cct.2005.05.002}}

\bibitem[\citeproctext]{ref-sennlewis2019treatment}
\CSLLeftMargin{16. }%
\CSLRightInline{Senn SJ, Lewis RJ. Treatment effects in multicenter
randomized clinical trials. \emph{JAMA}. 2019;321(12):1211-1212.
doi:\href{https://doi.org/10.1001/jama.2019.1553}{10.1001/jama.2019.1553}}

\bibitem[\citeproctext]{ref-neuhaus2006separating}
\CSLLeftMargin{17. }%
\CSLRightInline{Neuhaus JM, McCulloch CE. Separating between- and
within-cluster covariate effects by using conditional and partitioning
methods. \emph{Journal of the Royal Statistical Society: Series B}.
2006;68(5):859-872.
doi:\href{https://doi.org/10.1111/j.1467-9868.2006.00570.x}{10.1111/j.1467-9868.2006.00570.x}}

\bibitem[\citeproctext]{ref-ruvuna2004unequal}
\CSLLeftMargin{18. }%
\CSLRightInline{Ruvuna F. Unequal center sizes, sample size, and power
in multicenter clinical trials. \emph{Drug Information Journal}.
2004;38(4):387-394.
doi:\href{https://doi.org/10.1177/009286150403800409}{10.1177/009286150403800409}}

\bibitem[\citeproctext]{ref-vierron2009design}
\CSLLeftMargin{19. }%
\CSLRightInline{Vierron E, Giraudeau B. Design effect in multicenter
studies: Gain or loss of power? \emph{BMC Medical Research Methodology}.
2009;9:39.
doi:\href{https://doi.org/10.1186/1471-2288-9-39}{10.1186/1471-2288-9-39}}

\bibitem[\citeproctext]{ref-agresti2000strategies}
\CSLLeftMargin{20. }%
\CSLRightInline{Agresti A, Hartzel J. Strategies for comparing
treatments on a binary response with multi-centre data. \emph{Statistics
in Medicine}. 2000;19(8):1115-1139.
doi:\href{https://doi.org/10.1002/(SICI)1097-0258(20000430)19:8\%3C1115::AID-SIM408\%3E3.0.CO;2-X}{10.1002/(SICI)1097-0258(20000430)19:8\textless1115::AID-SIM408\textgreater3.0.CO;2-X}}

\bibitem[\citeproctext]{ref-morris2019using}
\CSLLeftMargin{21. }%
\CSLRightInline{Morris TP, White IR, Crowther MJ. Using simulation
studies to evaluate statistical methods. \emph{Statistics in Medicine}.
2019;38(11):2074-2102.
doi:\href{https://doi.org/10.1002/sim.8086}{10.1002/sim.8086}}

\bibitem[\citeproctext]{ref-iche9r1}
\CSLLeftMargin{22. }%
\CSLRightInline{International Council for Harmonisation. ICH {E9(R1)}:
Addendum on estimands and sensitivity analysis in clinical trials to the
guideline on statistical principles for clinical trials. Published
online 2019.
\url{https://database.ich.org/sites/default/files/E9-R1_Step4_Guideline_2019_1203.pdf}}

\bibitem[\citeproctext]{ref-kahanAccountingCentreeffectsMulticentre2014}
\CSLLeftMargin{23. }%
\CSLRightInline{Kahan BC. Accounting for centre-effects in multicentre
trials with a binary outcome -- when, why, and how? \emph{BMC Medical
Research Methodology}. 2014;14(1):20.
doi:\href{https://doi.org/10.1186/1471-2288-14-20}{10.1186/1471-2288-14-20}}

\bibitem[\citeproctext]{ref-sverdlovSelectingRandomizationMethod2024}
\CSLLeftMargin{24. }%
\CSLRightInline{Sverdlov O, Ryeznik Y, Anisimov V, et al. Selecting a
randomization method for a multi-center clinical trial with stochastic
recruitment considerations. \emph{BMC Medical Research Methodology}.
2024;24(1):52.
doi:\href{https://doi.org/10.1186/s12874-023-02131-z}{10.1186/s12874-023-02131-z}}

\end{CSLReferences}

\end{document}
